name: Mindful Long Beach
favicon: null
layout_spectrum: 0.9924115
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcbc4f'
    - '#ffffff'
    - '#000000'
    - '#8e6e01'
    - '#383838'
  brandStrength: 0.8887771
  lightness: 0.8436512
  saturation: 0
  rhythmicContrast: 0.8668395
purpose: []
