name: Mindful Long Beach
favicon: null
layout_spectrum: 0.74843
typography_spectrum: 0
title: MINDFUL LONG BEACH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcbc4f'
    - '#ffffff'
    - '#000000'
    - '#8e6e01'
    - '#383838'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
