layout_spectrum: 0.3594355
typography_spectrum: 0.1219077
color:
  saturation: 0.007339302
  lightness: 0.8436512
  brandStrength: 0.8887771
  rhythmicContrast: 0.8668395
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Mindful Long Beach
