title: MINDFUL LONG BEACH
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3046595
  brandStrength: 0.1875
  lightness: 0.4928315
  brandColors:
    - '#dcbc4f'
    - '#ffffff'
    - '#000000'
    - '#8e6e01'
    - '#383838'
  rhythmicContrast: 0.3566308
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Mindful Long Beach
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7383512
