title: MINDFUL LONG BEACH
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6917293
  brandStrength: 0.6458685
  lightness: 0.3640351
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#DDDDDD'
    - '#2F2550'
    - '#817F85'
  rhythmicContrast: 0.6365936
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Mindful Long Beach
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7383512
