name: Mindful Long Beach
favicon: null
layout_spectrum: 0.7383512
typography_spectrum: 0
title: MINDFUL LONG BEACH
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcbc4f'
    - '#ffffff'
    - '#000000'
    - '#8e6e01'
    - '#713667'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.7473118
purpose: []
