name: Mindful Long Beach
favicon: null
layout_spectrum: 0.74843
typography_spectrum: 0
title: MINDFUL LONG BEACH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dbba49'
    - '#000004'
    - '#916f03'
    - '#6a6976'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
