name: Mindful Long Beach
favicon: null
layout_spectrum: 0.7383512
typography_spectrum: 0
title: MINDFUL LONG BEACH
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#DBBA49'
    - '#C2C2C2'
    - '#000000'
    - '#9C7A0F'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
